# fly.toml app configuration file generated for digital-business-cards on 2024-03-28T06:04:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'digital-business-cards'
primary_region = 'yyz'

[build]
  [build.args]
    GO_VERSION = '1.21.6'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[files]]
  guest_path = "/.env"
  local_path = ".env"

[[files]]
  guest_path = "/serviceAccountKey.json"
  local_path = "serviceAccountKey.json"
